%% This script mainly draws the PPP calculation error curve
clear
clc
close all;
%% initialize variable
true_pos = [2.91978577101376e+06, -5.38374497439085e+06, 1.77460482916846e+06];% ABMF
vpa(true_pos)
floder_name = 'Products_Kalman_Static_G';% Data folder generated by MG-APP

%% red data
file_path = [floder_name '/' 'position.txt'];
[ spp_pos, ppp_pos,spp_vel, ppp_vel, time_vct ] = readText( file_path );

%% compute data; Switch to NEU
sol_PPP = ppp_pos;
bad_flag = find(sol_PPP(:,1)==0);
sol_PPP(bad_flag,:) = [];
time_vct(bad_flag,:) = [];
data_len = size(sol_PPP,1);
NEU1 = [];
for nk = 1:data_len
    dNEU1 = XYZ_NEU(sol_PPP(nk,:) , true_pos - sol_PPP(nk,:));
    NEU1 = [NEU1;dNEU1'];
end

%% plot data
X = time_vct;
figure;
hold on
plot(X, NEU1(:,1), 'r')
plot(X, NEU1(:,2), 'g')
plot(X, NEU1(:,3), 'b')
legend('N', 'E', 'U')
xlabel('GPS time(hour)')
ylabel('Error(m)')
grid on
legend('N', 'E', 'U')
ylim([-0.1 0.1])
