%% This script mainly draws the residual curve of PPP calculation
clear
clc
close all
%% read ppp file
floder_name = 'Products_Kalman_Static_G';% Data folder generated by MG-APP
file_path = [floder_name '/' 'Satellite_info.ppp'];
[ epochData, epoch_sat_num ] = read_ppp( file_path, 'G' );

%% get P code and L carrier residual
data_len = numel(epochData);
P_all = zeros(data_len, 40);
L_all = zeros(data_len, 40);
for i = 1: data_len
    allSat = epochData(i).SatData;
    for j = 1:numel(allSat)
        ep_Sat = allSat(j);
        L_all(i, ep_Sat.PRN) = ep_Sat.Correct(1);
        P_all(i, ep_Sat.PRN) = ep_Sat.Correct(2);
    end
end

%% plot figure
figure;
plot(L_all, '*')
title([' Carrier residual error'])
xlabel('epoch number')
ylabel('Error (m)')
legend_cell = cell(1,32);
for i = 1:32
    legend_cell{i} = num2str(i);
end
legend(legend_cell)

figure;
plot(P_all, '.')
title([' Pseudo-range residuals error'])
xlabel('epoch number')
ylabel('Error (m)')





